###############
##
####

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Segmentation'
  SESSION: 'ASSN'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 15
  NUM_EPOCHS: 200
  #NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-2
  LR_MIN: 1e-3
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 10
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 256
  TRAIN_DIR: 'H:/PPM-100-resize/' # path to training data
  VAL_DIR: 'H:/PPM-100-resize/'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  # SAVE_IMAGES: False
